name: CI (reusable)

on:
  workflow_call:
    inputs:
      matrix-os:
        type: string
        required: false
        default: '["ubuntu-latest","macos-latest","windows-latest"]'
      matrix-python:
        type: string
        required: false
        default: '["3.8","3.9","3.10","3.11","3.12","3.13"]'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
      - name: Run linting
        run: uv run ruff check .
      - name: Run type checking
        run: uv run basedpyright

  test:
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.matrix-os) }}
        python-version: ${{ fromJson(inputs.matrix-python) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: uv run pytest --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
