name: Daily check and release

on:
  # schedule:
  #   - cron: "0 2 * * *" # daily at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: daily-release
  cancel-in-progress: false

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Check and (if needed) update vendored vercel
        id: check
        run: |
          uv run python scripts/check_and_update.py

      - name: Commit changes
        if: steps.check.outputs.updated == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: vendor vercel@${{ steps.check.outputs.new_version }}"
          git push

      - name: Create tag
        if: steps.check.outputs.updated == 'true'
        run: |
          git tag v${{ steps.check.outputs.new_version }}
          git push origin v${{ steps.check.outputs.new_version }}

      - name: Build distribution
        if: steps.check.outputs.updated == 'true'
        run: |
          uv run --with build --with twine python -m build

      - name: Publish to PyPI
        if: steps.check.outputs.updated == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv run --with twine python -m twine upload --non-interactive dist/*
